quarkus:
  http:
    port: 8087
  swagger-ui:
    path: /api
    always-include: true 

  native:
    additional-build-args: -H:ReflectionConfigurationFiles=reflection-config.json

kafka:
  bootstrap:
    servers: localhost:9092

mp:
  messaging:
    outgoing:
      customer-out:
        connector: smallrye-kafka
        topic: customer
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
        merge: true

"%test":
  mp:
    messaging:
      outgoing:
        customer-out:
          connector: smallrye-kafka
